@url = http://localhost:8080/charinfo
@token =eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJpYXQiOjE3MjQyNzU1OTMsImV4cCI6MTcyNDI3OTE5M30.uploBme4pDsEluc_ED5-uE6NjN-byCxeJo6Z6b92Ek2u6yc98ZpDmf_J3lQzNNM-qQPEdszpOU8QPtvjCuKBUg
GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{url}}/mm HTTP/1.1
###
POST {{url}}
Content-Type: application/json

{
  "userID": "tesdt",
  "classType": "sorcerer",
  "level": 1,
  "race": "elf",
  "background": "sage",
  "exp": 1
}
###
PUT {{url}}/update/tests HTTP/1.1
Content-Type: application/json

{
  "userID": "asdf",
  "classType": "tests",
  "level": 1,
  "race": "test",
  "background": "test",
  "exp": 1
}
###
DELETE  {{url}}/delete/test HTTP/1.1
