@url = http://localhost:8080/api/abilityscore

GET {{url}}/user HTTP/1.1
###
GET {{url}}/user/test HTTP/1.1
###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "strength": 2,
    "dexterity": 2,
    "constitution": 2,
    "intelligence": 2,
    "wisdom": 2,
    "charisma": 2,
    "userID": "test" 
}
###
PUT {{url}}/user/test HTTP/1.1
Content-Type: application/json

{
    "asID": 1,
    "strength": 1,
    "dexterity": 2,
    "constitution": 3,
    "intelligence": 4,
    "wisdom": 5,
    "charisma": 6,
    "userID":"test"
}
