@url = http://localhost:8080/abilityscore

GET {{url}}/user HTTP/1.1
###
GET {{url}}/user/test HTTP/1.1
###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "strength": 8,
    "dexterity": 10,
    "constitution": 11,
    "intelligence": 13,
    "wisdom": 12,
    "charisma": 11,
    "userID": "reeb" 
}
###
PUT {{url}}/user/test HTTP/1.1
Content-Type: application/json

{
    "asID": 1,
    "strength": 1,
    "dexterity": 2,
    "constitution": 3,
    "intelligence": 4,
    "wisdom": 5,
    "charisma": 6,
    "userID":"test"
}
